### ISSUE TITLE
Next release 1.3 ?

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#186]
**New** 
- [x] Help menu rewrite - Issue https://github.com/Construkted-Reality/construkted_reality/issues/175 
- [x] Update CesiumJs to latest version - Issue https://github.com/Construkted-Reality/construkted_reality/issues/177
- [x] Underground/Underwater assets refinements - Issue https://github.com/Construkted-Reality/construkted_reality/issues/184
- [x] FLY speed Difference - Issue https://github.com/Construkted-Reality/construkted_reality/issues/182
- [x] Private assets displayed incorrectly - Issue https://github.com/Construkted-Reality/construkted_reality/issues/153 
- [x] Cesium 3D tile import functionality - Issue https://github.com/Construkted-Reality/construkted_reality/issues/157, Issue https://github.com/Construkted-Reality/construkted_api/issues/28

**Bugs**
- [x] Help menu icons - Issue https://github.com/Construkted-Reality/construkted_reality/issues/188
- [x] Underwater asset line update - Issue https://github.com/Construkted-Reality/construkted_reality/issues/192
- [x] 3D Tile Underground asset yellow line termination - Issue https://github.com/Construkted-Reality/construkted_reality/issues/193
- [x] iframe embed not working - Issue https://github.com/Construkted-Reality/construkted_reality/issues/202
- [x] Geo-Location styling change 02 - Issue https://github.com/Construkted-Reality/construkted_reality/issues/198

**Comment by Construkted-Reality** [comment]
- Please merge the branches for the issues listed in master.
- Create new release for version 1.3
- Update GW3 so I can test all the issues

**Comment by 3DGISKing** [comment]
All were merged. Some bugs were founded during my testing.

1. Help menu rewrite - Issue #175
     
![image](https://user-images.githubusercontent.com/26606704/110966726-8aac2980-8390-11eb-989d-fa43ccc255ba.png)

   The help menu looks tabbed window but I couldn't switch any other tab.

2.  Update CesiumJs to latest version - Issue #177
   If the asset is marked as "underground", a yellow line would not be displayed.

**Comment by Construkted-Reality** [comment]
![image](https://user-images.githubusercontent.com/13057505/110969284-80554580-8326-11eb-8a76-db59d0673fb6.png)
2. Works properly in my testing.

The asset has to be under the terrain for the yellow line to appear.

**Comment by Construkted-Reality** [comment]
Stefan has submitted a fix to the help menu icons in branch **188_helpoverlayicons**

Please incorporate branch **188_helpoverlayicons** into release 1.3 so I can test

**Comment by 3DGISKing** [comment]
yes

**Comment by 3DGISKing** [comment]
188_helpoverlayicons was merged to the master branch.
And the issue157-3dtile-import branch was rebased onto the master branch.

**Comment by Construkted-Reality** [comment]
Has issue [153](https://github.com/Construkted-Reality/construkted_reality/issues/153) been merged?

**Comment by 3DGISKing** [comment]
not sure. let me check.

**Comment by Construkted-Reality** [comment]
I checked. It's merged.
