### ISSUE TITLE
Release 1.4

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#187]
- [x] Reduce Bing Maps sessions calls : https://github.com/Construkted-Reality/construkted_reality/issues/205
- [x] Estimate Altitude logic change : https://github.com/Construkted-Reality/construkted_reality/issues/201
- [x] Geo-location workflow : https://github.com/Construkted-Reality/construkted_reality/issues/207
- [x] Geo-Location workflow for geo-referenced 3d tile upload asset ; https://github.com/Construkted-Reality/construkted_reality/issues/210
- [x] Geo-Location styling change 01 : https://github.com/Construkted-Reality/construkted_reality/issues/197
- [x] "Underground Asset" checkbox : https://github.com/Construkted-Reality/construkted_reality/issues/195
- [x] Cesium Ion Label : https://github.com/Construkted-Reality/construkted_reality/issues/209
- [x] Training and Scanning Services ; https://github.com/Construkted-Reality/construkted_reality/issues/194
- [x] Globe Test v2 ; https://github.com/Construkted-Reality/construkted_reality/issues/185

## Bugs
- [x] Footer Text : https://github.com/Construkted-Reality/construkted_reality/issues/208
